layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 20
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: willems.davy.5
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: joyrider3774
  # unsplash: your_username
  # vk: your_username
  website: http://www.willemssoft.be
  youtube: joyirder3774

topics:
  - name: Delphi
    web_url: https://www.embarcadero.com/products/delphi
    image_url: https://www.embarcadero.com/images/logos/logo-page/Delphi_FINAL_ICONS_1024.png

  - name: SDL
    web_url: https://www.libsdl.org
    image_url: https://www.libsdl.org/media/SDL_logo.png
    
  - name: Playnite
    web_url: https://www.playnite.link/
    image_url: https://www.playnite.link/applogo.png

  - name: Fuze 4 Nintendo Switch
    web_url: https://www.fuze.co.uk/
    image_url: https://www.joyrider3774.xyz/tmp/FUZE.png

  - name: Playdate by Panic
    web_url: https://play.date/
    image_url: https://static-cdn.play.date/static/images/apple-touch-icon.588a13acdab4.png
     
  - name: Game Development
  
  - name: Emulation
  
  - name: Virtual Pinball
